version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${MSSQL_PASSWORD}
    ports:
      - "${MSSQL_PORT}:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "80:3000"
    depends_on:
      - mssql
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "${MOSQUITTO_PORT}:1883"
    environment:
      MOSQUITTO_USERNAME: ${MOSQUITTO_USERNAME}
      MOSQUITTO_PASSWORD: ${MOSQUITTO_PASSWORD}
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always

  event_drive:
    image: synthblue/event_drive:v1
    container_name: event_drive
    depends_on:
      - mssql
      - mosquitto
    volumes:
      - .:/app
    working_dir: /app
    command: python main.py
    env_file:
      - .env
    restart: always

volumes:
  mssql_data:
  grafana_data:
  mosquitto_data:
